// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvUaUQKbpNTBhm8dsO8Pj7oIyUsaGwC74',
    appId: '1:804302455985:web:178875690c499d2e2fce90',
    messagingSenderId: '804302455985',
    projectId: 'guardian-net-alerts',
    authDomain: 'guardian-net-alerts.firebaseapp.com',
    storageBucket: 'guardian-net-alerts.firebasestorage.app',
    measurementId: 'G-7TFSYMVGM3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC04x-CuU_lmYBr9j-8_3oM8m5ikeePpxE',
    appId: '1:804302455985:android:a9447a792ff379bd2fce90',
    messagingSenderId: '804302455985',
    projectId: 'guardian-net-alerts',
    storageBucket: 'guardian-net-alerts.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHZCUu2yF20UDOV-fA203ldNINtT3-7Sg',
    appId: '1:804302455985:ios:b1e474ed38c553cc2fce90',
    messagingSenderId: '804302455985',
    projectId: 'guardian-net-alerts',
    storageBucket: 'guardian-net-alerts.firebasestorage.app',
    iosBundleId: 'com.example.guardianNet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHZCUu2yF20UDOV-fA203ldNINtT3-7Sg',
    appId: '1:804302455985:ios:b1e474ed38c553cc2fce90',
    messagingSenderId: '804302455985',
    projectId: 'guardian-net-alerts',
    storageBucket: 'guardian-net-alerts.firebasestorage.app',
    iosBundleId: 'com.example.guardianNet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvUaUQKbpNTBhm8dsO8Pj7oIyUsaGwC74',
    appId: '1:804302455985:web:5d0c0b1639efe4f32fce90',
    messagingSenderId: '804302455985',
    projectId: 'guardian-net-alerts',
    authDomain: 'guardian-net-alerts.firebaseapp.com',
    storageBucket: 'guardian-net-alerts.firebasestorage.app',
    measurementId: 'G-0J0HYZ77KX',
  );
}
